<<<<<<< HEAD
<?php /* Smarty version 2.6.27, created on 2014-02-27 21:24:52
=======
<?php /* Smarty version 2.6.27, created on 2014-02-26 23:07:16
>>>>>>> 74a3abfbee3de615f24a5c17dc5c915dbee51c31
         compiled from body.default.tpl */ ?>
<?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'pasteWord', 'body.default.tpl', 8, false),array('function', 'plugin', 'body.default.tpl', 60, false),array('function', 'region', 'body.default.tpl', 61, false),array('modifier', 'escape', 'body.default.tpl', 42, false),)), $this); ?>
<?php echo '<div class="page-wrapper"><div class="page-buffer"><!--cap block--><div class="cap'; ?><?php if ($this->_tpl_vars['page']['id'] == 1): ?><?php echo ' main-page'; ?><?php endif; ?><?php echo '"><div class="centerpos"><a href="/" class="logo" title=\''; ?><?php echo content::nullMethod(array('name' => 'logo_tag_title'), $this);?><?php echo '\'><img src="/img/logo.png" alt=\''; ?><?php echo content::nullMethod(array('name' => 'logo_tag_alt'), $this);?><?php echo '\' /></a><div class="contacts"><span>+7(343)-253-01-00</span><a href="#" class="callme">Заказать звонок</a><a href="#" class="mailme">Написать письмо</a></div><div class="cart"><a href="#" class="order"><div class="icon"></div><div class="data"><span class="count-label" data-type="count"></span><span>Всего на:&nbsp;<b><span data-type="cost"></span>&nbsp;<span data-type="currency_symbol"></span></b></span><span class="info">Нажмите сюда, чтобы оформить заказ</span></div></a></div><nav>'; ?><?php $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => "mmenu.tpl", 'smarty_include_vars' => array()));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
 ?><?php echo '</nav></div></div><!--END cap block--><!--content block--><div class="content"><div class="centerpos">'; ?><?php if (isset ( $this->_tpl_vars['breadcrumbs'] ) && count ( $this->_tpl_vars['breadcrumbs'] ) > 2): ?><?php echo '<ul class="breadcrumbs">'; ?><?php $_from = $this->_tpl_vars['breadcrumbs']; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }if (count($_from)):
    foreach ($_from as $this->_tpl_vars['crumb']):
?><?php echo '<li>'; ?><?php if (isset ( $this->_tpl_vars['crumb']['url'] )): ?><?php echo '<a href="'; ?><?php echo $this->_tpl_vars['crumb']['url']; ?><?php echo '">'; ?><?php echo ((is_array($_tmp=$this->_tpl_vars['crumb']['name'])) ? $this->_run_mod_handler('escape', true, $_tmp) : smarty_modifier_escape($_tmp)); ?><?php echo '</a>'; ?><?php else: ?><?php echo '<span>'; ?><?php echo ((is_array($_tmp=$this->_tpl_vars['crumb']['name'])) ? $this->_run_mod_handler('escape', true, $_tmp) : smarty_modifier_escape($_tmp)); ?><?php echo '</span>'; ?><?php endif; ?><?php echo '</li>'; ?><?php endforeach; endif; unset($_from); ?><?php echo '</ul>'; ?><?php endif; ?><?php echo ''; ?><?php if ($this->_tpl_vars['page']['id'] == 1): ?><?php echo '<div class="border"></div>'; ?><?php endif; ?><?php echo ''; ?><?php if ($this->_tpl_vars['page']['h1'] != ''): ?><?php echo '<h1 class="page-title">'; ?><?php echo $this->_tpl_vars['page']['h1']; ?><?php echo '</h1>'; ?><?php endif; ?><?php echo '<div class="text">'; ?><?php echo content::nullMethod(array('name' => 'catalog'), $this);?><?php echo ''; ?><?php echo content::addTemplateRegion(array('name' => 'beforecontent','runame' => "До контента"), $this);?><?php echo ''; ?><?php echo $this->_tpl_vars['page']['content']; ?><?php echo ''; ?><?php echo content::addTemplateRegion(array('name' => 'aftercontent','runame' => "После контента"), $this);?><?php echo '</div>'; ?><?php if (isset ( $this->_tpl_vars['breadcrumbs'] ) && count ( $this->_tpl_vars['breadcrumbs'] ) > 2): ?><?php echo '<ul class="breadcrumbs bottom">'; ?><?php $_from = $this->_tpl_vars['breadcrumbs']; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }if (count($_from)):
    foreach ($_from as $this->_tpl_vars['crumb']):
?><?php echo '<li>'; ?><?php if (isset ( $this->_tpl_vars['crumb']['url'] )): ?><?php echo '<a href="'; ?><?php echo $this->_tpl_vars['crumb']['url']; ?><?php echo '">'; ?><?php echo ((is_array($_tmp=$this->_tpl_vars['crumb']['name'])) ? $this->_run_mod_handler('escape', true, $_tmp) : smarty_modifier_escape($_tmp)); ?><?php echo '</a>'; ?><?php else: ?><?php echo '<span>'; ?><?php echo ((is_array($_tmp=$this->_tpl_vars['crumb']['name'])) ? $this->_run_mod_handler('escape', true, $_tmp) : smarty_modifier_escape($_tmp)); ?><?php echo '</span>'; ?><?php endif; ?><?php echo '</li>'; ?><?php endforeach; endif; unset($_from); ?><?php echo '</ul>'; ?><?php endif; ?><?php echo '</div></div><!--END content block--><!--push for footer--><div class="page-push"></div><!--END push for footer--></div></div><div class="page-footer"><div class="centerpos"></div></div><a href="#" id="mmenu-btn"></a><a href="#" id="mmenu-btn-back">Назад</a>'; ?>