<?php /* Smarty version 2.6.27, created on 2014-02-26 23:07:16
         compiled from page.default.tpl */ ?>
<?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('modifier', 'escape', 'page.default.tpl', 4, false),)), $this); ?>
<?php echo '<!DOCTYPE html><html xmlns="http://www.w3.org/1999/xhtml"><head>'; ?><?php if ($this->_tpl_vars['page']['title'] != ''): ?><?php echo '<title>'; ?><?php echo ((is_array($_tmp=$this->_tpl_vars['page']['title'])) ? $this->_run_mod_handler('escape', true, $_tmp) : smarty_modifier_escape($_tmp)); ?><?php echo '</title>'; ?><?php endif; ?><?php echo ''; ?><?php if ($this->_tpl_vars['page']['meta_robots_all'] == '1'): ?><?php echo '<meta name="robots" content="all"/>'; ?><?php endif; ?><?php echo ''; ?><?php if ($this->_tpl_vars['page']['meta_robots_noindex'] == '1'): ?><?php echo '<meta name="robots" content="noindex"/>'; ?><?php endif; ?><?php echo ''; ?><?php if ($this->_tpl_vars['page']['meta_robots_nofollow'] == '1'): ?><?php echo '<meta name="robots" content="nofollow"/>'; ?><?php endif; ?><?php echo ''; ?><?php if ($this->_tpl_vars['page']['meta_robots_noarchive'] == '1'): ?><?php echo '<meta name="robots" content="noarchive"/>'; ?><?php endif; ?><?php echo ''; ?><?php if ($this->_tpl_vars['page']['skype_block'] == '1'): ?><?php echo '<meta name="SKYPE_TOOLBAR" content="SKYPE_TOOLBAR_PARSER_COMPATIBLE" />'; ?><?php endif; ?><?php echo '<meta http-equiv="content-type" content="text/html; charset='; ?><?php echo $this->_tpl_vars['page']['charset']; ?><?php echo '"/><meta content="'; ?><?php echo ((is_array($_tmp=$this->_tpl_vars['page']['author'])) ? $this->_run_mod_handler('escape', true, $_tmp) : smarty_modifier_escape($_tmp)); ?><?php echo '" name="author"/><meta content="'; ?><?php echo ((is_array($_tmp=$this->_tpl_vars['page']['copyright'])) ? $this->_run_mod_handler('escape', true, $_tmp) : smarty_modifier_escape($_tmp)); ?><?php echo '" name="dcterms.rights"/><!--<meta http-equiv="content-language" content="'; ?><?php echo $this->_tpl_vars['page']['language']; ?><?php echo '"/>--><meta name="description" content="'; ?><?php echo ((is_array($_tmp=$this->_tpl_vars['page']['description'])) ? $this->_run_mod_handler('escape', true, $_tmp) : smarty_modifier_escape($_tmp)); ?><?php echo '"/><meta name="keywords" content="'; ?><?php echo ((is_array($_tmp=$this->_tpl_vars['page']['keywords'])) ? $this->_run_mod_handler('escape', true, $_tmp) : smarty_modifier_escape($_tmp)); ?><?php echo '"/><link rel="icon" href="/img/favicon.ico" type="image/x-icon"/><link rel="shortcut icon" href="/img/favicon.ico" type="image/x-icon"/>'; ?><?php if ($this->_tpl_vars['page']['unite_css'] != '1'): ?><?php echo ''; ?><?php $_from = $this->_tpl_vars['metaBufferCssArray']; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }if (count($_from)):
    foreach ($_from as $this->_tpl_vars['href']):
?><?php echo '<link rel="stylesheet" type="text/css" href="'; ?><?php echo $this->_tpl_vars['href']; ?><?php echo '">'; ?><?php endforeach; endif; unset($_from); ?><?php echo ''; ?><?php else: ?><?php echo '<link rel="stylesheet" type="text/css" href="/css/styles.css"/>'; ?><?php endif; ?><?php echo '<link rel="stylesheet" type="text/css" href="/core.css"/>'; ?><?php $_from = $this->_tpl_vars['metaBufferLessArray']; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }if (count($_from)):
    foreach ($_from as $this->_tpl_vars['href']):
?><?php echo '<link rel="stylesheet/less" type="text/css" href="'; ?><?php echo $this->_tpl_vars['href']; ?><?php echo '">'; ?><?php endforeach; endif; unset($_from); ?><?php echo ''; ?><?php if ($this->_tpl_vars['page']['unite_js'] != '1'): ?><?php echo ''; ?><?php $_from = $this->_tpl_vars['metaBufferJsArray']; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }if (count($_from)):
    foreach ($_from as $this->_tpl_vars['src']):
?><?php echo '<script type="text/javascript" src="'; ?><?php echo $this->_tpl_vars['src']; ?><?php echo '"></script>'; ?><?php endforeach; endif; unset($_from); ?><?php echo ''; ?><?php else: ?><?php echo '<script type="text/javascript" src="/js/scripts.js"></script>'; ?><?php endif; ?><?php echo '<script type="text/javascript" src="/core.js"></script>'; ?><?php if ($this->_tpl_vars['editedFromAdmin']): ?><?php echo '<script type="text/javascript" src="/system/admin/editor/ckeditor/ckeditor.js"></script>'; ?><?php endif; ?><?php echo ''; ?><?php echo $this->_tpl_vars['page']['extra_meta']; ?><?php echo ''; ?><?php echo $this->_tpl_vars['page']['super_meta']; ?><?php echo '</head><body>'; ?><?php $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => ($this->_tpl_vars['body']), 'smarty_include_vars' => array()));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
 ?><?php echo '</body></html>'; ?>