<?php /* Smarty version 2.6.27, created on 2014-02-11 05:12:06
         compiled from comparePage.tpl */ ?>
<?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('modifier', 'escape', 'comparePage.tpl', 19, false),array('function', 'pasteWord', 'comparePage.tpl', 47, false),)), $this); ?>
<?php echo '<div class="plug_catalog catalog_compare_page"><h1>Сравнение</h1>'; ?><?php if (isset ( $this->_tpl_vars['empty'] )): ?><?php echo '<p>Пусто</p>'; ?><?php else: ?><?php echo ''; ?><?php $_from = $this->_tpl_vars['compareArray']; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }if (count($_from)):
    foreach ($_from as $this->_tpl_vars['typeId'] => $this->_tpl_vars['itemsArray']):
?><?php echo '<div class="full_block_compare"><p class="type_name">'; ?><?php echo $this->_tpl_vars['itemsArray']['type_name']; ?><?php echo '</p><div class="compare_all_wrapper"><table class="titles" cellpadding="0" cellspacing="0"><tbody><tr class="image"><td><span></span></td></tr><tr><td><span>Название</span></td></tr><tr><td><span>Цена</span></td></tr>'; ?><?php $_from = $this->_tpl_vars['itemsArray']['attr_list']; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }if (count($_from)):
    foreach ($_from as $this->_tpl_vars['attrId'] => $this->_tpl_vars['attrData']):
?><?php echo '<tr><td><span>'; ?><?php echo ((is_array($_tmp=$this->_tpl_vars['attrData']['attribute_name'])) ? $this->_run_mod_handler('escape', true, $_tmp) : smarty_modifier_escape($_tmp)); ?><?php echo ''; ?><?php if ($this->_tpl_vars['attrData']['attribute_units'] != ''): ?><?php echo '('; ?><?php echo $this->_tpl_vars['attrData']['attribute_units']; ?><?php echo ')'; ?><?php endif; ?><?php echo '</span></td></tr>'; ?><?php endforeach; endif; unset($_from); ?><?php echo '<tr><td><span>Производитель</span></td></tr><tr><td><span></span></td></tr></tbody></table><div class="compare_wrapper"><div class="compare_block">'; ?><?php $_from = $this->_tpl_vars['itemsArray']['items']; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }if (count($_from)):
    foreach ($_from as $this->_tpl_vars['itemId'] => $this->_tpl_vars['item']):
?><?php echo '<table data-id="'; ?><?php echo $this->_tpl_vars['itemId']; ?><?php echo '" cellpadding="0" cellspacing="0"><tbody><tr class="image"><td><span>'; ?><?php if ($this->_tpl_vars['item']['item_logo'] != ''): ?><?php echo '<img src="'; ?><?php echo $this->_tpl_vars['item']['item_logo']; ?><?php echo '" />'; ?><?php else: ?><?php echo '<div class="no_photo"></div>'; ?><?php endif; ?><?php echo '</span><a href="#" class="delete" data-id="'; ?><?php echo $this->_tpl_vars['itemId']; ?><?php echo '"></a>'; ?><?php if ($this->_tpl_vars['item']['in_stock'] == '0'): ?><?php echo '<span class="not_in_stock">Товара нет в наличии</span>'; ?><?php endif; ?><?php echo '</td></tr><tr class="name"><td><span>'; ?><?php echo ((is_array($_tmp=$this->_tpl_vars['item']['name'])) ? $this->_run_mod_handler('escape', true, $_tmp) : smarty_modifier_escape($_tmp)); ?><?php echo '</span></td></tr><tr  class="price"><td><span>'; ?><?php echo $this->_tpl_vars['item']['price']; ?><?php echo '&nbsp;'; ?><?php echo $this->_tpl_vars['catalog']['currency_symbol']; ?><?php echo '</span></td></tr>'; ?><?php $_from = $this->_tpl_vars['item']['attributes']; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }if (count($_from)):
    foreach ($_from as $this->_tpl_vars['attrId'] => $this->_tpl_vars['attrData']):
?><?php echo '<tr><td><span>'; ?><?php echo ((is_array($_tmp=$this->_tpl_vars['attrData']['attribute_value'])) ? $this->_run_mod_handler('escape', true, $_tmp) : smarty_modifier_escape($_tmp)); ?><?php echo '</span></td></tr>'; ?><?php endforeach; endif; unset($_from); ?><?php echo '<tr><td><span><a href="'; ?><?php echo $this->_tpl_vars['item']['full_brand_url']; ?><?php echo '" title="Перейти на страницу производителя" class="brand">'; ?><?php echo $this->_tpl_vars['item']['brand_name']; ?><?php echo '</a></span></td></tr><tr><td>'; ?><?php if ($this->_tpl_vars['item']['is_new'] == '1'): ?><?php echo '<a href="#" class="buy -new" data-id="'; ?><?php echo $this->_tpl_vars['item']['id']; ?><?php echo '"><span><i></i>'; ?><?php echo $this->_tpl_vars['item']['price']; ?><?php echo '&nbsp;'; ?><?php echo $this->_tpl_vars['catalog']['currency_symbol']; ?><?php echo '</span>'; ?><?php echo core::templatePasteWord(array('name' => 'plug_index_catalog_buy'), $this);?><?php echo '</a>'; ?><?php elseif ($this->_tpl_vars['item']['is_sale'] == '1'): ?><?php echo '<a href="#" class="buy -sale" data-id="'; ?><?php echo $this->_tpl_vars['item']['id']; ?><?php echo '"><span><i></i><b class="old">'; ?><?php echo $this->_tpl_vars['item']['old_price']; ?><?php echo '&nbsp;'; ?><?php echo $this->_tpl_vars['catalog']['currency_symbol']; ?><?php echo '</b><b class="new">	'; ?><?php echo $this->_tpl_vars['item']['price']; ?><?php echo '&nbsp;'; ?><?php echo $this->_tpl_vars['catalog']['currency_symbol']; ?><?php echo '</b></span>'; ?><?php echo core::templatePasteWord(array('name' => 'plug_index_catalog_buy'), $this);?><?php echo '</a>'; ?><?php elseif ($this->_tpl_vars['item']['is_best'] == '1'): ?><?php echo '<a href="#" class="buy -best" data-id="'; ?><?php echo $this->_tpl_vars['item']['id']; ?><?php echo '"><span><i></i>'; ?><?php echo $this->_tpl_vars['item']['price']; ?><?php echo '&nbsp;'; ?><?php echo $this->_tpl_vars['catalog']['currency_symbol']; ?><?php echo '</span>'; ?><?php echo core::templatePasteWord(array('name' => 'plug_index_catalog_buy'), $this);?><?php echo '</a>'; ?><?php else: ?><?php echo '<a href="#" class="buy" data-id="'; ?><?php echo $this->_tpl_vars['item']['id']; ?><?php echo '"><span><i></i>'; ?><?php echo $this->_tpl_vars['item']['price']; ?><?php echo '&nbsp;'; ?><?php echo $this->_tpl_vars['catalog']['currency_symbol']; ?><?php echo '</span>'; ?><?php echo core::templatePasteWord(array('name' => 'plug_index_catalog_buy'), $this);?><?php echo '</a>'; ?><?php endif; ?><?php echo '</td></tr></tbody></table>'; ?><?php endforeach; endif; unset($_from); ?><?php echo '</div></div></div></div>'; ?><?php endforeach; endif; unset($_from); ?><?php echo ''; ?><?php endif; ?><?php echo '</div>'; ?>