<?php /* Smarty version 2.6.27, created on 2014-02-14 22:39:37
         compiled from cat_list.menu.tpl */ ?>
<?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('modifier', 'escape', 'cat_list.menu.tpl', 19, false),)), $this); ?>
<?php echo '<ul class="categories">'; ?><?php $_from = $this->_tpl_vars['categories']; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }if (count($_from)):
    foreach ($_from as $this->_tpl_vars['key'] => $this->_tpl_vars['cat']):
?><?php echo '<li>'; ?><?php if ($this->_tpl_vars['catalog']['current_cat_id'] == 0 && ! isset ( $this->_tpl_vars['filterArray'] )): ?><?php echo '<a href="'; ?><?php echo $this->_tpl_vars['cat']['full_url']; ?><?php echo '"><div class="image">'; ?><?php if (isset ( $this->_tpl_vars['cat']['full_logo_src'] )): ?><?php echo '<img width="200" height="200" src="'; ?><?php echo $this->_tpl_vars['cat']['full_logo_src']; ?><?php echo '" />'; ?><?php else: ?><?php echo '<div class="no_photo"></div>'; ?><?php endif; ?><?php echo '</div><div class="descrblock"><div class="name"><strong>'; ?><?php echo ((is_array($_tmp=$this->_tpl_vars['cat']['name'])) ? $this->_run_mod_handler('escape', true, $_tmp) : smarty_modifier_escape($_tmp)); ?><?php echo '</strong></div><div class="descr">As soon as Dagny marked a new issue, he got a notification by email and now he is reviewing Dagny\'s comments, snapshot of the buggy part of the website and technical details - what device, OS and browser Dagny was using.As soon as Dagny marked a new issue, he got a notification by email and now he is reviewing Dagny\'s comments, snapshot of the buggy part of the website and technical details - what device, OS and browser Dagny was using.</div></div><div class="lineblock"></div></a>'; ?><?php else: ?><?php echo '<a href="'; ?><?php echo $this->_tpl_vars['cat']['full_url']; ?><?php echo '">'; ?><?php echo ((is_array($_tmp=$this->_tpl_vars['cat']['name'])) ? $this->_run_mod_handler('escape', true, $_tmp) : smarty_modifier_escape($_tmp)); ?><?php echo '</a>'; ?><?php endif; ?><?php echo ''; ?><?php $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => "cat_list.menu.tpl", 'smarty_include_vars' => array('categories' => $this->_tpl_vars['cat']['childNodes'])));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
 ?><?php echo '</li>'; ?><?php endforeach; endif; unset($_from); ?><?php echo '</ul>'; ?>