<?php /* Smarty version 2.6.27, created on 2014-02-10 20:28:27
         compiled from cat_list.menu.tpl */ ?>
<?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('modifier', 'escape', 'cat_list.menu.tpl', 8, false),)), $this); ?>
<?php echo '<ul>'; ?><?php $_from = $this->_tpl_vars['categories']; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }if (count($_from)):
    foreach ($_from as $this->_tpl_vars['key'] => $this->_tpl_vars['item']):
?><?php echo '<li><a href="#" class="node_ctrl plus" data-id="'; ?><?php echo $this->_tpl_vars['item']['id']; ?><?php echo '"></a><a href="'; ?><?php echo $this->_tpl_vars['item']['url']; ?><?php echo '" data-get="page" data-action="'; ?><?php echo $this->_tpl_vars['item']['id']; ?><?php echo '" class="'; ?><?php if ($this->_tpl_vars['item']['off'] == '1'): ?><?php echo 'disabled'; ?><?php endif; ?><?php echo ''; ?><?php if ($this->_tpl_vars['item']['hide'] == '1'): ?><?php echo ' hidden'; ?><?php endif; ?><?php echo ''; ?><?php if (isset ( $this->_tpl_vars['currentCatId'] ) && $this->_tpl_vars['currentCatId'] == $this->_tpl_vars['item']['id']): ?><?php echo ' act'; ?><?php endif; ?><?php echo '">'; ?><?php echo ((is_array($_tmp=$this->_tpl_vars['item']['name'])) ? $this->_run_mod_handler('escape', true, $_tmp) : smarty_modifier_escape($_tmp)); ?><?php echo '</a>'; ?><?php if ($this->_tpl_vars['item']['off'] == '1'): ?><?php echo '<span class="hlp" title="В настройках данной категории отмечен пункт &laquo;Не доступна&raquo;. Это означает, что при попытке перейти в данную категорию будет сгенерирована ошибка 404 - страница не найдена"></span>'; ?><?php endif; ?><?php echo ''; ?><?php if ($this->_tpl_vars['item']['hide'] == '1'): ?><?php echo '<span class="hlp" title="В настройках данной категории отмечен пункт &laquo;Скрыть из списка категорий&raquo;. Это означает, что категория не показывается в списке категорий сайта"></span>'; ?><?php endif; ?><?php echo '<a href="#" class="edit" title="Редактировать категорию." data-id="'; ?><?php echo $this->_tpl_vars['item']['id']; ?><?php echo '" ></a><a href="#" class="add" title="Добавить подкатегорию." data-pid="'; ?><?php echo $this->_tpl_vars['item']['id']; ?><?php echo '" ></a><a href="#" class="delete" title="Удалить категорию." data-id="'; ?><?php echo $this->_tpl_vars['item']['id']; ?><?php echo '" data-name="'; ?><?php echo $this->_tpl_vars['item']['name']; ?><?php echo '"></a>'; ?><?php $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => "cat_list.menu.tpl", 'smarty_include_vars' => array('categories' => $this->_tpl_vars['item']['childNodes'])));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
 ?><?php echo '</li>'; ?><?php endforeach; endif; unset($_from); ?><?php echo '</ul>'; ?>